name: TPBan
version: 1.0
main: moyumc.TPBan
api-version: 1.21
description: A plugin that teleports banned players to a specific location
commands:
  tpban:
    description: Teleport ban a player
    usage: /tpban <player> <time> <reason>
    permission: tpban.command
    permission-message: You don't have permission to use this command!
    aliases: [tban]
  tpban_setxyz:
    description: Set the TP ban location
    usage: /tpban_setxyz
    permission: tpban.admin
    permission-message: You don't have permission to use this command!
    aliases: [setbanloc]